version: '3.8'
services:
  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      target: rails-builder
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/number_two_dev
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      BINDING: 0.0.0.0
    restart: always
volumes:
  pg-data:
